//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HB_InsideEntities : DbContext
    {
        public HB_InsideEntities()
            : base("name=HB_InsideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gen_organizasyon> gen_organizasyon { get; set; }
        public DbSet<gen_personel> gen_personel { get; set; }
        public DbSet<mesaj> mesaj { get; set; }
        public DbSet<personel_oturum> personel_oturum { get; set; }
        public DbSet<personel_tur> personel_tur { get; set; }
    
        public virtual ObjectResult<PR_TELEFON_NO_KONTROL_Result> PR_TELEFON_NO_KONTROL(string p_TEL_NO)
        {
            var p_TEL_NOParameter = p_TEL_NO != null ?
                new ObjectParameter("P_TEL_NO", p_TEL_NO) :
                new ObjectParameter("P_TEL_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_TELEFON_NO_KONTROL_Result>("PR_TELEFON_NO_KONTROL", p_TEL_NOParameter);
        }
    }
}
