//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_personel
    {
        public gen_personel()
        {
            this.mesaj = new HashSet<mesaj>();
            this.personel_oturum = new HashSet<personel_oturum>();
        }
    
        public int SICIL_KOD { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string SIFRE { get; set; }
        public string ULKE_KOD { get; set; }
        public Nullable<decimal> ORG_NO { get; set; }
        public decimal SW_BORDRO_ALT_BIRIM { get; set; }
        public string POZISYON { get; set; }
        public string CINSIYET { get; set; }
        public Nullable<System.DateTime> DOGUM_TARIHI { get; set; }
        public string MEDENI_DURUM { get; set; }
        public string KAN_GRUBU { get; set; }
        public Nullable<System.DateTime> ISE_GIRIS_TARIHI { get; set; }
        public Nullable<System.DateTime> ISTEN_CIKIS_TARIHI { get; set; }
        public Nullable<decimal> SIRKET_NO { get; set; }
        public string TC_KIMLIK_NO { get; set; }
        public string SSK_NO { get; set; }
        public string ADRES { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string EMAIL { get; set; }
        public string EGITIM { get; set; }
        public Nullable<decimal> MUHASEBE_KODU { get; set; }
        public Nullable<decimal> SW_USTALIK { get; set; }
        public string NAR_HESABI_GRUBU { get; set; }
        public Nullable<decimal> SW_MERKEZ_URETIM { get; set; }
        public Nullable<decimal> POSTA_KOD { get; set; }
        public string SICIL_KAYNAK { get; set; }
        public string YONETICI_1 { get; set; }
        public string YONETICI_2 { get; set; }
        public string YONETICI_3 { get; set; }
        public Nullable<decimal> SORUMLU_ORG_1 { get; set; }
        public Nullable<decimal> SORUMLU_ORG_2 { get; set; }
        public Nullable<decimal> SORUMLU_ORG_3 { get; set; }
        public string CALISMA_GRUBU { get; set; }
        public decimal EKLEYEN_KULLANICI { get; set; }
        public System.DateTime EKLENEN_TARIH { get; set; }
        public Nullable<decimal> GUNCELLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> GUNCELLENEN_TARIH { get; set; }
        public Nullable<decimal> SW_AKTIF { get; set; }
        public string POZISYON_ACIKLAMA { get; set; }
        public Nullable<decimal> SAP_ORG_KOD { get; set; }
        public string SAP_ORG_ACIKLAMA { get; set; }
        public Nullable<decimal> BMS_FABRIKA_KOD { get; set; }
        public Nullable<decimal> BMS_URUN_GRUP_KOD { get; set; }
        public Nullable<decimal> BMS_HAT_KOD { get; set; }
        public Nullable<decimal> BMS_GRUP_KOD { get; set; }
        public Nullable<decimal> BMS_EKIP_KOD { get; set; }
        public Nullable<decimal> BMS_DEPARTMAN_KOD { get; set; }
    
        public virtual gen_organizasyon gen_organizasyon { get; set; }
        public virtual gen_organizasyon gen_organizasyon1 { get; set; }
        public virtual gen_organizasyon gen_organizasyon2 { get; set; }
        public virtual gen_organizasyon gen_organizasyon3 { get; set; }
        public virtual gen_organizasyon gen_organizasyon4 { get; set; }
        public virtual gen_organizasyon gen_organizasyon5 { get; set; }
        public virtual gen_organizasyon gen_organizasyon6 { get; set; }
        public virtual gen_organizasyon gen_organizasyon7 { get; set; }
        public virtual gen_organizasyon gen_organizasyon8 { get; set; }
        public virtual gen_organizasyon gen_organizasyon9 { get; set; }
        public virtual ICollection<mesaj> mesaj { get; set; }
        public virtual ICollection<personel_oturum> personel_oturum { get; set; }
        public virtual personel_tur personel_tur { get; set; }
    }
}
