//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_oturum
    {
        public int SICIL_KOD { get; set; }
        public System.DateTime OTURUM_BASLANGIC_TARIH { get; set; }
        public System.DateTime OTURUM_BITIS_TARIH { get; set; }
        public string BEARER_TOKEN { get; set; }
        public int ID { get; set; }
    
        public virtual gen_personel gen_personel { get; set; }
    }
}
